language: ruby
sudo: false
cache: bundler
rvm:
  - 2.1
  - 2.2
  - 2.3.0
  - 2.3.1
  - ruby-head
matrix:
  allow_failures:
    - rvm: ruby-head
before_install:
  - gem update --system
  - gem install bundler
  - gem --version
