language: ruby
sudo: false
cache:
  bundler: true
  apt: true
addons:
  apt:
    packages:
      - libgd2-xpm
      - ia32-libs
      - ia32-libs-multiarch
      - binutils
os:
- linux
- osx
rvm:
  - 2.1
  - 2.2
  - 2.3
  - 2.4.0
  - ruby-head
matrix:
  allow_failures:
    - rvm: ruby-head
before_install:
  - gem update --system
  - gem install bundler
  - gem --version
